FROM openjdk:8

RUN mkdir /usr/myapp

COPY service/service_note/target/service_note-1.0-SNAPSHOT.jar /usr/myapp

WORKDIR /usr/myapp

ENTRYPOINT ["java", "-jar", "-Xmx256m", "service_note-1.0-SNAPSHOT.jar"]