server:
  port: 9000

spring:
  application:
    name: cloud-notebook-user
  cloud:
    nacos:
      discovery:
        server-addr: 43.139.60.130:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 'jdbc:mysql://119.91.234.58:3306/cloud_notebook?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false'
    username: root
    password: linpeibiaoxiaohu
  # session 失效时间
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # redis 配置
  redis:
    port: 6379
    host: 119.91.234.58
    database: 2
    password: linpeibiaoxiaohu

  # rabbitmq 配置
  rabbitmq:
    host: 119.91.234.58
    port: 5672
    username: xiaohu
    password: 123456
    publisher-confirm-type: correlated

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)